/**
 * Style Dictionary v4 configuration — ZoePlane Design Token Pipeline
 *
 * Generated by: Sprint Programmer (Story 2.1)
 * Source of truth: docs/design/dark-mode-architecture.md (v1.1)
 *
 * Architecture: DTCG W3C v1 three-tier cascade
 *   Layer 1 (tokens.base)      — Primitives (theme-invariant OKLCH ramps)
 *   Layer 2 (tokens.semantic)  — Semantic (theme-branching: light + dark)
 *   Layer 3 (tokens.component) — Component (theme-invariant; references semantic)
 *   + Typography, Spacing, Shape, Motion, Layout layers
 *
 * Output: ../../src/styles/tokens.css
 *
 * IMPORTANT: Do NOT run Style Dictionary's default CSS formatter.
 * We use a custom formatter that emits the exact three-tier @layer structure
 * expected by ZoePlane's Tailwind v4 + Vite pipeline. The DTCG JSON in
 * src/tokens.seed.json holds the primitive color values; everything else is
 * authored directly in this formatter to ensure semantic equivalence with the
 * hand-authored canonical file (490 lines) that this pipeline replaces.
 */

import StyleDictionary from "style-dictionary";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Custom formatter — emits the full ZoePlane tokens.css structure
// ---------------------------------------------------------------------------

StyleDictionary.registerFormat({
  name: "zoeplaneTokensCSS",
  format: function ({ dictionary }) {
    // Pull primitive color values from the dictionary so they stay in sync
    // with tokens.seed.json. Everything else is authored here directly.
    const tok = (path) => {
      const token = dictionary.allTokens.find((t) => t.path.join(".") === path);
      if (!token) {
        throw new Error(`[style-dictionary] Missing token: ${path} — check tokens.seed.json`);
      }
      // Style Dictionary v4 with DTCG tokens uses $value (not value)
      return token["$value"] ?? token.value;
    };

    return `/*
 * ZoePlane Design Tokens — DTCG W3C v1, October 2025
 * Three-tier architecture: Primitives → Semantic → Component
 *
 * Source of truth: docs/design/dark-mode-architecture.md (v1.1)
 * Companion: docs/design/ux-spec.md §2 (typography, spacing, radius, elevation, motion)
 *
 * Generated by Style Dictionary v4 — see packages/design-tokens/style-dictionary.config.mjs
 * DO NOT hand-edit this file. Edit packages/design-tokens/src/tokens.seed.json and run:
 *   bun run tokens:build
 *
 * RULES:
 *  - Layer 1 (Primitives): theme-invariant. NEVER consumed by components directly.
 *  - Layer 2 (Semantic): the ONLY layer that branches on theme.
 *  - Layer 3 (Component): theme-invariant; consumes semantic tokens only.
 *  - Components MUST NOT branch on theme (no \`data-theme === "dark"\` in component code).
 */

/* ============================================================
   LAYER 1 — PRIMITIVES (theme-invariant)
   All color primitives use OKLCH for perceptual uniformity.
   WCAG: see dark-mode-architecture.md contrast checklist.
   ============================================================ */
@layer tokens.base {
  :root {
    /* ---- Neutrals — single ramp; both themes pull from this ---- */
    --gray-50:   ${tok("color.gray.50")};
    --gray-100:  ${tok("color.gray.100")};
    --gray-200:  ${tok("color.gray.200")};
    --gray-300:  ${tok("color.gray.300")};
    --gray-400:  ${tok("color.gray.400")};
    --gray-500:  ${tok("color.gray.500")};
    --gray-600:  ${tok("color.gray.600")};
    --gray-700:  ${tok("color.gray.700")};
    --gray-800:  ${tok("color.gray.800")};
    --gray-850:  ${tok("color.gray.850")};
    --gray-900:  ${tok("color.gray.900")};
    --gray-950:  ${tok("color.gray.950")};
    --gray-975:  ${tok("color.gray.975")};

    /* ---- Brand accent — hue 260 (brand blue) ---- */
    --accent-50:  ${tok("color.accent.50")};
    --accent-100: ${tok("color.accent.100")};
    --accent-200: ${tok("color.accent.200")};
    --accent-400: ${tok("color.accent.400")};
    --accent-500: ${tok("color.accent.500")};
    --accent-600: ${tok("color.accent.600")};
    --accent-700: ${tok("color.accent.700")};
    --accent-800: ${tok("color.accent.800")};

    /* ---- Status primitives ---- */
    --success-400: ${tok("color.success.400")};
    --success-500: ${tok("color.success.500")};
    --success-600: ${tok("color.success.600")};

    --warn-400: ${tok("color.warn.400")};
    --warn-500: ${tok("color.warn.500")};
    --warn-600: ${tok("color.warn.600")};

    --danger-400: ${tok("color.danger.400")};
    --danger-500: ${tok("color.danger.500")};
    --danger-600: ${tok("color.danger.600")};

    /* ---- Info — hue 220 (NEW v1.1, distinct from accent 260)
       Used for Soft Notification "pending review" hooks.
       40 hue-degrees away from accent so badge ≠ "Review" CTA button. ---- */
    --info-400: ${tok("color.info.400")};
    --info-500: ${tok("color.info.500")};
    --info-600: ${tok("color.info.600")};

    /* ---- Quarantine — hue 320 (NEW v1.1, "purple-amber" composite)
       Strict Mode quarantined hooks. Distinct from warn (75), danger (25), accent (260).
       Signals "held/blocked" without the urgency of red. ---- */
    --quarantine-400: ${tok("color.quarantine.400")};
    --quarantine-500: ${tok("color.quarantine.500")};
    --quarantine-600: ${tok("color.quarantine.600")};

    /* ---- Event-family hues (NEW v1.1) — HookCard event chips
       De-saturated (chroma 0.06–0.10) so chip reads as category label, not status.
       Groups:
         tool family    (PreToolUse / PostToolUse) — hue 200 (cool blue-cyan)
         session family (SessionStart / Stop / SubagentStop) — hue 160 (teal)
         prompt family  (UserPromptSubmit / Notification) — hue 280 (violet)
         compact family (PreCompact, singleton) — hue 60 (warm khaki) ---- */
    --event-family-tool-500:         ${tok("color.event-family.tool-500")};
    --event-family-tool-muted:       ${tok("color.event-family.tool-muted")};
    --event-family-tool-muted-dark:  ${tok("color.event-family.tool-muted-dark")};

    --event-family-session-500:          ${tok("color.event-family.session-500")};
    --event-family-session-muted:        ${tok("color.event-family.session-muted")};
    --event-family-session-muted-dark:   ${tok("color.event-family.session-muted-dark")};

    --event-family-prompt-500:          ${tok("color.event-family.prompt-500")};
    --event-family-prompt-muted:        ${tok("color.event-family.prompt-muted")};
    --event-family-prompt-muted-dark:   ${tok("color.event-family.prompt-muted-dark")};

    --event-family-compact-500:         ${tok("color.event-family.compact-500")};
    --event-family-compact-muted:       ${tok("color.event-family.compact-muted")};
    --event-family-compact-muted-dark:  ${tok("color.event-family.compact-muted-dark")};
  }
}

/* ============================================================
   LAYER 2 — SEMANTIC (theme-dependent — only layer that branches)
   LIGHT is the default; DARK overrides via [data-theme="dark"].
   Every token defined in light MUST be defined in dark — enforced by CI.
   ============================================================ */
@layer tokens.semantic {

  /* ---- LIGHT (default) ---- */
  :root,
  :root[data-theme="light"] {
    /* Surfaces */
    --color-background:       var(--gray-50);
    --color-surface:          white;
    --color-surface-raised:   white;
    --color-surface-overlay:  white;
    --color-surface-muted:    var(--gray-100);
    --color-surface-sunken:   var(--gray-100);

    /* Text */
    --color-foreground:              var(--gray-900);
    --color-foreground-muted:        var(--gray-600);
    --color-foreground-subtle:       var(--gray-500);
    --color-foreground-on-accent:    white;
    --color-foreground-disabled:     var(--gray-400);

    /* Borders & dividers */
    --color-border:        var(--gray-200);
    --color-border-strong: var(--gray-300);
    --color-border-subtle: var(--gray-100);
    --color-border-focus:  var(--accent-600);

    /* Brand / interactive */
    --color-accent:            var(--accent-600);
    --color-accent-hover:      var(--accent-700);
    --color-accent-active:     var(--accent-800);
    --color-accent-muted:      var(--accent-100);
    --color-accent-foreground: white;

    /* Status: success */
    --color-success:            var(--success-600);
    --color-success-muted:      oklch(0.950 0.030 150);
    --color-success-foreground: white;

    /* Status: warning
       NOTE: warning foreground is gray-900 in BOTH themes — yellow has chronic
       contrast trouble against white text. See dark-mode-architecture.md. */
    --color-warning:            var(--warn-600);
    --color-warning-muted:      oklch(0.960 0.040 75);
    --color-warning-foreground: var(--gray-900);

    /* Status: danger */
    --color-danger:            var(--danger-600);
    --color-danger-muted:      oklch(0.960 0.030 25);
    --color-danger-foreground: white;

    /* Info — REDEFINED v1.1: distinct hue 220 (not aliased to accent 260).
       The Soft Notification "pending review" badge sits next to the "Review"
       CTA button (accent). Same hue would merge them visually. */
    --color-info:            var(--info-600);
    --color-info-muted:      oklch(0.955 0.040 220);
    --color-info-foreground: white;

    /* Quarantine — NEW v1.1: Strict Mode "quarantined — *" badge.
       Purple-amber composite hue 320. */
    --color-quarantine:            var(--quarantine-600);
    --color-quarantine-muted:      oklch(0.955 0.040 320);
    --color-quarantine-foreground: white;

    /* Event-family tones — LIGHT */
    --color-event-family-tool:             var(--event-family-tool-500);
    --color-event-family-tool-muted:       var(--event-family-tool-muted);
    --color-event-family-session:          var(--event-family-session-500);
    --color-event-family-session-muted:    var(--event-family-session-muted);
    --color-event-family-prompt:           var(--event-family-prompt-500);
    --color-event-family-prompt-muted:     var(--event-family-prompt-muted);
    --color-event-family-compact:          var(--event-family-compact-500);
    --color-event-family-compact-muted:    var(--event-family-compact-muted);

    /* Selection / interaction */
    --color-selection:     oklch(0.880 0.080 260);
    --color-hover-overlay: rgb(0 0 0 / 0.04);
    --color-focus-ring:    var(--accent-600);

    /* Code / mono */
    --color-code-background: var(--gray-100);
    --color-code-foreground:  var(--gray-900);

    /* Workflow Builder canvas */
    --color-canvas-background: oklch(0.975 0.005 250);
    --color-canvas-grid:        var(--gray-200);

    /* Task Console per-agent-pane border tints */
    --color-pane-running:   var(--success-500);
    --color-pane-approval:  var(--warn-500);
    --color-pane-error:     var(--danger-500);
    --color-pane-completed: var(--gray-300);

    /* Scrollbar */
    --color-scrollbar-thumb: var(--gray-300);
    --color-scrollbar-track: transparent;
  }

  /* ---- DARK ---- */
  :root[data-theme="dark"] {
    /* Surfaces */
    --color-background:       var(--gray-950);
    --color-surface:          var(--gray-900);
    --color-surface-raised:   var(--gray-850);
    --color-surface-overlay:  var(--gray-800);
    --color-surface-muted:    var(--gray-900);
    --color-surface-sunken:   var(--gray-975);

    /* Text */
    --color-foreground:              var(--gray-50);
    --color-foreground-muted:        var(--gray-400);
    --color-foreground-subtle:       var(--gray-500);
    --color-foreground-on-accent:    white;
    --color-foreground-disabled:     var(--gray-600);

    /* Borders & dividers */
    --color-border:        var(--gray-800);
    --color-border-strong: var(--gray-700);
    --color-border-subtle: var(--gray-850);
    --color-border-focus:  var(--accent-400);

    /* Brand / interactive
       IMPORTANT: hover inverts direction in dark — hover gets BRIGHTER (accent-200
       vs accent-400 base). This is correct: hover must increase contrast against
       the (now dark) surface. See dark-mode-architecture.md notable mapping decisions. */
    --color-accent:            var(--accent-400);
    --color-accent-hover:      var(--accent-200);
    --color-accent-active:     var(--accent-100);
    --color-accent-muted:      oklch(0.230 0.080 260);
    /* Accent foreground inverts: accent-400 is lighter so white fails contrast;
       gray-950 is used instead. */
    --color-accent-foreground: var(--gray-950);

    /* Status: success */
    --color-success:            var(--success-400);
    --color-success-muted:      oklch(0.230 0.060 150);
    --color-success-foreground: var(--gray-950);

    /* Status: warning — foreground stays dark in both themes (yellow + white = fail) */
    --color-warning:            var(--warn-400);
    --color-warning-muted:      oklch(0.250 0.080 75);
    --color-warning-foreground: var(--gray-950);

    /* Status: danger */
    --color-danger:            var(--danger-400);
    --color-danger-muted:      oklch(0.250 0.080 25);
    --color-danger-foreground: var(--gray-950);

    /* Info — REDEFINED v1.1 */
    --color-info:            var(--info-400);
    --color-info-muted:      oklch(0.245 0.080 220);
    --color-info-foreground: var(--gray-950);

    /* Quarantine — NEW v1.1 */
    --color-quarantine:            var(--quarantine-400);
    --color-quarantine-muted:      oklch(0.250 0.080 320);
    --color-quarantine-foreground: var(--gray-950);

    /* Event-family tones — DARK
       Foreground hue values are the same (500 step reads in both themes);
       muted backgrounds flip to dark variants. */
    --color-event-family-tool:             var(--event-family-tool-500);
    --color-event-family-tool-muted:       var(--event-family-tool-muted-dark);
    --color-event-family-session:          var(--event-family-session-500);
    --color-event-family-session-muted:    var(--event-family-session-muted-dark);
    --color-event-family-prompt:           var(--event-family-prompt-500);
    --color-event-family-prompt-muted:     var(--event-family-prompt-muted-dark);
    --color-event-family-compact:          var(--event-family-compact-500);
    --color-event-family-compact-muted:    var(--event-family-compact-muted-dark);

    /* Selection / interaction */
    --color-selection:     oklch(0.380 0.150 260);
    --color-hover-overlay: rgb(255 255 255 / 0.05);
    --color-focus-ring:    var(--accent-400);

    /* Code / mono */
    --color-code-background: var(--gray-975);
    --color-code-foreground:  var(--gray-100);

    /* Workflow Builder canvas */
    --color-canvas-background: oklch(0.110 0.008 250);
    --color-canvas-grid:        var(--gray-800);

    /* Task Console per-agent-pane border tints */
    --color-pane-running:   var(--success-400);
    --color-pane-approval:  var(--warn-400);
    --color-pane-error:     var(--danger-400);
    --color-pane-completed: var(--gray-700);

    /* Scrollbar */
    --color-scrollbar-thumb: var(--gray-700);
    --color-scrollbar-track: transparent;
  }
}

/* ============================================================
   LAYER 3 — COMPONENT (theme-invariant; consumes semantic tokens)
   Same expression in light and dark — variation is entirely upstream.
   Add component tokens here as components are built in their epics.
   ============================================================ */
@layer tokens.component {
  :root {
    /* ---- Buttons ---- */
    --button-primary-bg:       var(--color-accent);
    --button-primary-fg:       var(--color-accent-foreground);
    --button-primary-bg-hover: var(--color-accent-hover);
    --button-primary-bg-active: var(--color-accent-active);

    --button-ghost-bg:       transparent;
    --button-ghost-fg:       var(--color-foreground);
    --button-ghost-bg-hover: var(--color-hover-overlay);

    --button-destructive-bg:       var(--color-danger);
    --button-destructive-fg:       var(--color-danger-foreground);
    --button-destructive-bg-hover: oklch(from var(--color-danger) calc(l - 0.05) c h);

    /* ---- Cards ---- */
    --card-bg:     var(--color-surface);
    --card-border: var(--color-border);
    /* Card hover: slight elevation via border-strong; no shadow change on desktop */
    --card-border-hover: var(--color-border-strong);

    /* ---- Inputs ---- */
    --input-bg:           var(--color-surface);
    --input-border:       var(--color-border-strong);
    --input-border-focus: var(--color-border-focus);
    --input-fg:           var(--color-foreground);
    --input-placeholder:  var(--color-foreground-subtle);

    /* ---- Task Console pane borders ---- */
    --pane-running-border:   var(--color-pane-running);
    --pane-approval-border:  var(--color-pane-approval);
    --pane-error-border:     var(--color-pane-error);
    --pane-completed-border: var(--color-pane-completed);

    /* TODO (Epic 02 Sprint 1): expand with Badge, Modal, Sidebar, TitleBar,
       CommandPalette, LibraryShell, EvaluatorStatusBadge component tokens.
       See ux-spec §8.1 (Foundation tier) and §8.2 (Layout tier). */
  }
}

/* ============================================================
   TYPOGRAPHY TOKENS (theme-invariant — same scale for both themes)
   Fluid type scale using clamp() — adjusts to window width without breakpoints.
   Per ux-spec §2.2.
   ============================================================ */
@layer tokens.typography {
  :root {
    /* Font families */
    --font-sans:    'Inter', -apple-system, 'SF Pro Text', system-ui, sans-serif;
    --font-mono:    'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace;
    --font-display: 'Inter Display', 'Inter', -apple-system, sans-serif;

    /* Type scale — fluid via clamp(min, preferred, max) */
    --text-xs:   clamp(0.75rem,  0.73rem + 0.1vw,   0.8125rem);  /* 12 → 13px */
    --text-sm:   clamp(0.875rem, 0.85rem + 0.125vw,  0.9375rem); /* 14 → 15px */
    --text-base: clamp(1rem,     0.95rem + 0.25vw,   1.0625rem); /* 16 → 17px */
    --text-lg:   clamp(1.125rem, 1.05rem + 0.375vw,  1.25rem);   /* 18 → 20px */
    --text-xl:   clamp(1.25rem,  1.15rem + 0.5vw,    1.5rem);    /* 20 → 24px */
    --text-2xl:  clamp(1.5rem,   1.3rem  + 1vw,      2rem);      /* 24 → 32px */
    --text-3xl:  clamp(1.875rem, 1.6rem  + 1.4vw,    2.5rem);    /* 30 → 40px */
    /* NOTE: ux-spec stops at --text-3xl. Add --text-4xl here if PRD §5-B
       designates a display-only size above 3xl (currently no spec for it). */

    /* Mono type scale — for streaming agent output, code, file paths */
    --text-mono-sm:   clamp(0.8125rem, 0.79rem + 0.1vw,  0.875rem);
    --text-mono-base: clamp(0.9375rem, 0.9rem  + 0.15vw, 1rem);

    /* Font weights */
    --weight-regular:  400;
    --weight-medium:   500;
    --weight-semibold: 600;
    --weight-bold:     700;

    /* Line heights */
    --leading-tight:   1.2;
    --leading-snug:    1.35;
    --leading-normal:  1.5;
    --leading-relaxed: 1.625;

    /* Letter spacing — minimal; caps/labels only */
    --tracking-tight:  -0.01em;
    --tracking-normal: 0;
    --tracking-wide:   0.025em;
  }
}

/* ============================================================
   SPACING TOKENS (theme-invariant, 4px base)
   Per ux-spec §2.3.
   ============================================================ */
@layer tokens.spacing {
  :root {
    --space-0:    0;
    --space-px:   1px;
    --space-0_5:  2px;
    --space-1:    4px;
    --space-1_5:  6px;
    --space-2:    8px;
    --space-2_5:  10px;
    --space-3:    12px;
    --space-4:    16px;
    --space-5:    20px;
    --space-6:    24px;
    --space-8:    32px;
    --space-10:   40px;
    --space-12:   48px;
    --space-16:   64px;
    --space-20:   80px;
    --space-24:   96px;
  }
}

/* ============================================================
   RADIUS & ELEVATION TOKENS (theme-invariant except shadows — see dark overrides)
   Per ux-spec §2.4.
   ============================================================ */
@layer tokens.shape {
  :root {
    --radius-sm:   4px;
    --radius:      6px;      /* default for cards, inputs, buttons */
    --radius-md:   8px;
    --radius-lg:   12px;     /* modals, popovers */
    --radius-xl:   16px;
    --radius-full: 9999px;   /* pills, avatars */

    /* Elevation — light: subtle drop shadows */
    --shadow-sm: 0 1px 2px rgb(0 0 0 / 0.05);
    --shadow:    0 1px 3px rgb(0 0 0 / 0.08), 0 1px 2px rgb(0 0 0 / 0.04);
    --shadow-md: 0 4px 6px rgb(0 0 0 / 0.07), 0 2px 4px rgb(0 0 0 / 0.04);
    --shadow-lg: 0 10px 15px rgb(0 0 0 / 0.08), 0 4px 6px rgb(0 0 0 / 0.05);
  }

  /* Dark shadows are denser — but elevation in dark leans more on surface tone
     (surface-raised is lighter than surface) than on shadows alone. */
  :root[data-theme="dark"] {
    --shadow-sm: 0 1px 2px rgb(0 0 0 / 0.5);
    --shadow:    0 2px 4px rgb(0 0 0 / 0.5), 0 1px 2px rgb(0 0 0 / 0.4);
    --shadow-md: 0 4px 8px rgb(0 0 0 / 0.5), 0 2px 4px rgb(0 0 0 / 0.4);
    --shadow-lg: 0 10px 20px rgb(0 0 0 / 0.5), 0 4px 8px rgb(0 0 0 / 0.4);
  }
}

/* ============================================================
   MOTION TOKENS (theme-invariant)
   Per ux-spec §2.5. The prefers-reduced-motion override is the load-bearing
   implementation: zeroing durations here makes ALL transitions instant without
   requiring per-component reduced-motion branches.
   ============================================================ */
@layer tokens.motion {
  :root {
    --motion-duration-fast:    ${tok("motion.duration.fast")};
    --motion-duration-base:    ${tok("motion.duration.base")};
    --motion-duration-slow:    ${tok("motion.duration.slow")};

    --motion-easing-standard:   ${tok("motion.easing.standard")};
    --motion-easing-decelerate: ${tok("motion.easing.decelerate")};
    --motion-easing-accelerate: ${tok("motion.easing.accelerate")};
  }

  @media (prefers-reduced-motion: reduce) {
    :root {
      --motion-duration-fast:    0ms;
      --motion-duration-base:    0ms;
      --motion-duration-slow:    0ms;
    }
  }
}

/* ============================================================
   BREAKPOINTS (theme-invariant)
   Single-window v1 — breakpoints govern internal layout response to
   user-resized windows, not device sizes. Per ux-spec §2.6.
   ============================================================ */
@layer tokens.layout {
  :root {
    --bp-compact:     1024px;  /* hide inspector by default; sidebar can collapse */
    --bp-comfortable: 1280px;  /* default working size; all three panes visible */
    --bp-spacious:    1536px;  /* generous; canvases get extra padding */
  }
}
`;
  },
});

// ---------------------------------------------------------------------------
// Style Dictionary configuration
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: ["src/tokens.seed.json"],
  platforms: {
    css: {
      transformGroup: "css",
      files: [
        {
          destination: "../../src/styles/tokens.css",
          format: "zoeplaneTokensCSS",
          options: {
            outputReferences: false,
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
